const manufacturers = [
  { field: "acura", label: "Acura" },
  { field: "alfa_romeo", label: "Alfa Romeo" },
  { field: "aston_martin", label: "Aston Martin" },
  { field: "audi", label: "Audi" },
  { field: "bentley", label: "Bentley" },
  { field: "bmw", label: "BMW" },
  { field: "bugatti", label: "Bugatti" },
  { field: "chevrolet", label: "Chevrolet" },
  { field: "chrysler", label: "Chrysler" },
  { field: "citroen", label: "Citroën" },
  { field: "dodge", label: "Dodge" },
  { field: "ferrari", label: "Ferrari" },
  { field: "fiat", label: "Fiat" },
  { field: "ford", label: "Ford" },
  { field: "honda", label: "Honda" },
  { field: "hyundai", label: "Hyundai" },
  { field: "infiniti", label: "Infiniti" },
  { field: "jaguar", label: "Jaguar" },
  { field: "jeep", label: "Jeep" },
  { field: "kia", label: "Kia" },
  { field: "lamborghini", label: "Lamborghini" },
  { field: "land_rover", label: "Land Rover" },
  { field: "lexus", label: "Lexus" },
  { field: "maserati", label: "Maserati" },
  { field: "mazda", label: "Mazda" },
  { field: "mcLaren", label: "McLaren" },
  { field: "mercedes", label: "Mercedes-Benz" },
  { field: "mitsubishi", label: "Mitsubishi" },
  { field: "nissan", label: "Nissan" },
  { field: "peugeot", label: "Peugeot" },
  { field: "porsche", label: "Porsche" },
  { field: "ram", label: "RAM" },
  { field: "renault", label: "Renault" },
  { field: "rolls_royce", label: "Rolls-Royce" },
  { field: "skoda", label: "Škoda" },
  { field: "subaru", label: "Subaru" },
  { field: "suzuki", label: "Suzuki" },
  { field: "tesla", label: "Tesla" },
  { field: "toyota", label: "Toyota" },
  { field: "volkswagen", label: "Volkswagen" },
  { field: "volvo", label: "Volvo" },
];

export default manufacturers;
